name: Run Tests

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install Ginkgo
      run: go get github.com/onsi/ginkgo/ginkgo

    - name: Build Binaries
      run: make binaries

    - name: Run Unit Tests
      run: make test
